# Generated by Django 2.2.4 on 2019-08-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='model',
        ),
    ]
