# Generated by Django 2.2.4 on 2019-08-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20190815_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(),
        ),
    ]
